{"uuid":"96742f94-c409-4d87-8967-7ca285eb9c16","name":"Scenario Outline: The user getting error message with invalid python code for Types of Linked List","children":["003c5dc0-bb50-4511-8fde-b34c58ee9291"],"befores":[],"afters":[{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696724574943,"stop":1696724574944},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696724575014,"stop":1696724575014},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696724575120,"stop":1696724575120},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696724577146,"stop":1696724577147}],"start":1696724574730,"stop":1696724577148}