{"uuid":"d5757196-4d16-4bcc-89b7-91a40bf853f9","name":"Scenario Outline: The user getting error message with invalid python code for Types of Linked List","children":["7811a705-3048-4cd3-9251-ca6bf7fd486b"],"befores":[],"afters":[{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696720480462,"stop":1696720480463},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696720480558,"stop":1696720480559},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696720480608,"stop":1696720480608},{"name":"Hooks.Hooks.a(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696720482629,"stop":1696720482629}],"start":1696720480319,"stop":1696720482630}